# Generated by Django 3.2.5 on 2021-07-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service_location',
            field=models.ManyToManyField(related_name='Service_Location', to='authentication.ServiceLocation'),
        ),
    ]
